# Tool versions and download URLs with SHA256 checksums
# This file defines the pinned versions of external tools used by BazBOM

# Note: Semgrep is distributed via PyPI and should be installed using:
# pipx install semgrep==1.141.0
# or: pip install semgrep==1.141.0
# See: https://semgrep.dev/docs/getting-started/
[semgrep]
version = "1.142.0"
install_method = "pypi"  # Not downloaded by BazBOM - user must install via pip/pipx

[codeql]
version = "2.23.3"

[codeql.linux_x86_64]
url = "https://github.com/github/codeql-cli-binaries/releases/download/v2.23.3/codeql-linux64.zip"
sha256 = "9866d7c40aa182b950f99ad4594c9fe36c2172ee9673da1d302dc56fe82183e5"
archive = true
executable = "codeql/codeql"

[codeql.macos_x86_64]
url = "https://github.com/github/codeql-cli-binaries/releases/download/v2.23.3/codeql-osx64.zip"
sha256 = "37d8e06c3fe21f0a61283c6e95458440cecfef681da539375a8fd2614668b338"
archive = true
executable = "codeql/codeql"

[codeql.macos_aarch64]
url = "https://github.com/github/codeql-cli-binaries/releases/download/v2.23.3/codeql-osx64.zip"
sha256 = "37d8e06c3fe21f0a61283c6e95458440cecfef681da539375a8fd2614668b338"
archive = true
executable = "codeql/codeql"

[codeql.windows_x86_64]
url = "https://github.com/github/codeql-cli-binaries/releases/download/v2.23.3/codeql-win64.zip"
sha256 = "4fd0a039438ddc66f7f178cee9008686fe689f9e06e2cb7adc4bc73622220378"
archive = true
executable = "codeql/codeql.exe"

[syft]
version = "1.37.0"

[syft.linux_x86_64]
url = "https://github.com/anchore/syft/releases/download/v1.37.0/syft_1.37.0_linux_amd64.tar.gz"
sha256 = "b81a0dc81b92265f4597659bba5509e014c78228182804bb1bc97856af26e326"
archive = true
executable = "syft"

[syft.linux_aarch64]
url = "https://github.com/anchore/syft/releases/download/v1.37.0/syft_1.37.0_linux_arm64.tar.gz"
sha256 = "52980b7fd4829ab9561527c775c5adc7ece43eb7f9026e456351cd5b5252fdda"
archive = true
executable = "syft"

[syft.macos_x86_64]
url = "https://github.com/anchore/syft/releases/download/v1.37.0/syft_1.37.0_darwin_amd64.tar.gz"
sha256 = "70e00d20e3d0a72d90fdee607986f680cfaccc50c51a66e12030b96df62770cf"
archive = true
executable = "syft"

[syft.macos_aarch64]
url = "https://github.com/anchore/syft/releases/download/v1.37.0/syft_1.37.0_darwin_arm64.tar.gz"
sha256 = "b676cb2e112fcf5ec25638cca129f5de92f4786a6c4628cd3c307992f1a6a50d"
archive = true
executable = "syft"
